version: '3.8'

services:

  backend_fastapi:
    build: ./backend_fastapi
    ports:
      - 5000:5000

  frontend_streamlit:
    build: ./frontend_streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend_fastapi

  
